### ISSUE TITLE
Stuck on .desktop file.

### ISSUE THREAD

**Issue by Anonymous2716** [hanzala123/arch2appimage#2]
I'm on CLI only . but it asks for a .desktop file .what do I do now?

**Comment by redicculus** [comment]
I would probably assemble it from scratch:
https://docs.appimage.org/reference/desktop-integration.html#desktop-files

**Comment by Anonymous2716** [comment]
@redicculus how do I assemble those configs in the file? Any examples?

**Comment by hanzala123** [comment]
Hi, I am not sure what you mean by the question. This asks for the desktop file because there was no desktop file in the package. A desktop file is mandatory for making an AppImage. Making a .desktop file is pretty simple. You can learn about it [here](https://www.maketecheasier.com/create-desktop-file-linux/#:~:text=A%20%E2%80%9C.,local%20account%20or%20for%20everyone.). After making it copy the path to it and paste in the promt. The script should work file from there.

**Comment by LinuxWelt** [comment]
> Hi, I am not sure what you mean by the question.
The problem is that your .desktop file parser is broken or bogus.
It fails on "Categories=" among other things.

**Comment by Anonymous2716** [comment]
Ohkay. I still have to figure out some of it. But you can close the issue. Of not useful.

**Comment by hanzala123** [comment]
> > Hi, I am not sure what you mean by the question.
> 
> The problem is that your .desktop file parser is broken or just bogus. It fails on "Categories=" among other things.

HI @LinuxWelt, The `desktop-file-validate` tool is used to validate the .desktop file. This tool is part of the `desktop-file-utils` package which is the standard for working with .desktop files on linux. You can find more information on that [here](https://www.freedesktop.org/wiki/Software/desktop-file-utils/).
