### ISSUE TITLE
No cardpeek

### ISSUE THREAD

**Issue by Xdavius** [hanzala123/arch2appimage#24]
Hi,
I would like to make appimage of cardpeek but it isn't in Chaotic so... 
I think we really need suort from the official AUR or the use of localy build packages...

thanks

**Comment by hanzala123** [comment]
Hello, Both these features have been requested before. These are on the roadmap however since the first release of this project I have been extremely busy and wasn't able to make the changes. Any contributions are welcome. As these have been requested in the previous issues as well I am closing this.
